### ISSUE TITLE
Get different zone's picture

### ISSUE THREAD

**Issue by lord63** [lord63/wonderful_bing#17]

**Comment by lord63** [comment]
http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=YOURCHOICE
* Japan: ja-JP

**Comment by lord63** [comment]
It seems that I need a proxy.
If I don't use proxy in the browser, change the market parameter doesn't work at all, it always points to China.

**Comment by renzhn** [comment]
try it in curl, works here(China)

**Comment by lord63** [comment]
Hi, seems still chinese.

    $ curl http://www.bing.com/HPImageArchive.aspx\?format\=js\&idx\=0\&n\=1\&nc\=1409879295618\&pid\=hp1\&nc\=1409879295618\&pid\=hp\&mkt\=en-US
    {"images":[{"startdate":"20151119","fullstartdate":"201511191600","enddate":"20151120","url":"http://s.cn.bing.net/az/hprichbg/rb/Archie_ZH-CN11903785706_1920x1080.jpg","urlbase":"/az/hprichbg/rb/Archie_ZH-CN11903785706","copyright":"美国内布拉斯加州，哥伦比亚猛犸象标本 (© Joel Sartore/Getty Images)","copyrightlink":"http://www.bing.com/search?q=%E5%93%A5%E4%BC%A6%E6%AF%94%E4%BA%9A%E7%8C%9B%E7%8A%B8%E8%B1%A1&form=hpcapt&mkt=zh-cn","wp":true,"hsh":"b2351281b0ac808b9d0d2040aa402ecd","drk":1,"top":1,"bot":1,"hs":[{"desc":"蓝花楹掉落在青草上，蹄印刻在时间的年轮，","link":"http://www.bing.com/images/search?q=%E5%93%A5%E4%BC%A6%E6%AF%94%E4%BA%9A%E7%8C%9B%E7%8A%B8%E8%B1%A1&form=hphot1&mkt=zh-cn","query":"静止多年的水，轻轻晃动成冰。","locx":19,"locy":39},{"desc":"我喜爱一切不彻底的事情，琥珀里的时间，微暗的火，","link":"http://www.bing.com/images/search?q=%E7%90%A5%E7%8F%80&form=hphot2&mkt=zh-cn","query":"一生都在半途而废，一生都怀抱希望。","locx":32,"locy":43},{"desc":"还有一出发生在寒冷来袭前的默剧，","link":"http://www.bing.com/search?q=%E5%86%B0%E6%B2%B3%E4%B8%96%E7%BA%AA&form=hphot3&mkt=zh-cn","query":"被一只松鼠抢了戏……","locx":65,"locy":35}],"msg":[{"title":"今日图片故事","link":"http://www.bing.com/search?q=%E5%93%A5%E4%BC%A6%E6%AF%94%E4%BA%9A%E7%8C%9B%E7%8A%B8%E8%B1%A1&form=pgbar1&mkt=zh-cn","text":"哥伦比亚猛犸象标本"}]}],"tooltips":{"loading":"Loading...","previous":"Previous","next":"Next","walle":"This image is not available to download as wallpaper.","walls":"Download this image. Use of this image is restricted to wallpaper only."}}

**Comment by lord63** [comment]
It seems that use http://global.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US will do the trick.

**Comment by lord63** [comment]
Closed. Currently, we don't support specify zones, your'll get the pictures according to your ip.
